export const RESTAURANTS_SEED = [
  {
    name: 'Burger Town',
    cuisine: 'American',
    deliveryTimeMinutes: 25,
    rating: 4.3,
    deliveryFee: 2.49,
    isOpen: true,
    isFeatured: true,
    promoPercent: 20,
  },
  {
    name: 'Sushi Express',
    cuisine: 'Japanese',
    deliveryTimeMinutes: 35,
    rating: 4.8,
    deliveryFee: 3.99,
    isOpen: true,
    isFeatured: false,
    promoPercent: 0,
  },
  {
    name: 'Pasta Place',
    cuisine: 'Italian',
    deliveryTimeMinutes: 30,
    rating: 4.6,
    deliveryFee: 1.99,
    isOpen: false,
    isFeatured: true,
    promoPercent: 15,
  },
  {
    name: 'Taco Haven',
    cuisine: 'Mexican',
    deliveryTimeMinutes: 20,
    rating: 4.1,
    deliveryFee: 0.99,
    isOpen: true,
    isFeatured: false,
    promoPercent: 10,
  },
  {
    name: 'Pizza Planet',
    cuisine: 'Italian',
    deliveryTimeMinutes: 40,
    rating: 4.4,
    deliveryFee: 2.99,
    isOpen: true,
    isFeatured: true,
    promoPercent: 25,
  },
  {
    name: 'Wok Works',
    cuisine: 'Chinese',
    deliveryTimeMinutes: 30,
    rating: 4.2,
    deliveryFee: 1.5,
    isOpen: true,
    isFeatured: false,
    promoPercent: 0,
  },
  {
    name: 'Salad Stop',
    cuisine: 'Healthy',
    deliveryTimeMinutes: 15,
    rating: 4.7,
    deliveryFee: 4.49,
    isOpen: true,
    isFeatured: false,
    promoPercent: 5,
  },
  {
    name: 'Curry Corner',
    cuisine: 'Indian',
    deliveryTimeMinutes: 45,
    rating: 4.5,
    deliveryFee: 2.5,
    isOpen: true,
    isFeatured: true,
    promoPercent: 10,
  },
  {
    name: 'The Bagel Bar',
    cuisine: 'Breakfast',
    deliveryTimeMinutes: 10,
    rating: 4.9,
    deliveryFee: 0.0,
    isOpen: true,
    isFeatured: false,
    promoPercent: 0,
  },
  {
    name: 'Pho House',
    cuisine: 'Vietnamese',
    deliveryTimeMinutes: 25,
    rating: 4.3,
    deliveryFee: 3.49,
    isOpen: false,
    isFeatured: false,
    promoPercent: 0,
  },
];
